In [1]:
import pandas as pd


ur1 = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data?authuser=0"
columns = ['id','diagnosis'] + [f'feature_{i}' for i in range(1,31)]
data = pd.read_csv(ur1, header=None, names=columns)

data.drop(columns=['id'] , inplace=True)

data.to_csv('breast_cancer_wisconsin.csv', index=False)



In [2]:
data

diagnosis  feature_1  feature_2  feature_3  feature_4  feature_5  \
0           M      17.99      10.38     122.80     1001.0    0.11840   
1           M      20.57      17.77     132.90     1326.0    0.08474   
2           M      19.69      21.25     130.00     1203.0    0.10960   
3           M      11.42      20.38      77.58      386.1    0.14250   
4           M      20.29      14.34     135.10     1297.0    0.10030   
..        ...        ...        ...        ...        ...        ...   
564         M      21.56      22.39     142.00     1479.0    0.11100   
565         M      20.13      28.25     131.20     1261.0    0.09780   
566         M      16.60      28.08     108.30      858.1    0.08455   
567         M      20.60      29.33     140.10     1265.0    0.11780   
568         B       7.76      24.54      47.92      181.0    0.05263   

     feature_6  feature_7  feature_8  feature_9  ...  feature_21  feature_22  \
0      0.27760    0.30010    0.14710     0.2419  ...      25.380       17.33   
1      0.07864    0.08690    0.07017     0.1812  ...      24.990       23.41   
2      0.15990    0.19740    0.12790     0.2069  ...      23.570       25.53   
3      0.28390    0.24140    0.10520     0.2597  ...      14.910       26.50   
4      0.13280    0.19800    0.10430     0.1809  ...      22.540       16.67   
..         ...        ...        ...        ...  ...         ...         ...   
564    0.11590    0.24390    0.13890     0.1726  ...      25.450       26.40   
565    0.10340    0.14400    0.09791     0.1752  ...      23.690       38.25   
566    0.10230    0.09251    0.05302     0.1590  ...      18.980       34.12   
567    0.27700    0.35140    0.15200     0.2397  ...      25.740       39.42   
568    0.04362    0.00000    0.00000     0.1587  ...       9.456       30.37   

     feature_23  feature_24  feature_25  feature_26  feature_27  feature_28  \
0        184.60      2019.0     0.16220     0.66560      0.7119      0.2654   
1        158.80      1956.0     0.12380     0.18660      0.2416      0.1860   
2        152.50      1709.0     0.14440     0.42450      0.4504      0.2430   
3         98.87       567.7     0.20980     0.86630      0.6869      0.2575   
4        152.20      1575.0     0.13740     0.20500      0.4000      0.1625   
..          ...         ...         ...         ...         ...         ...   
564      166.10      2027.0     0.14100     0.21130      0.4107      0.2216   
565      155.00      1731.0     0.11660     0.19220      0.3215      0.1628   
566      126.70      1124.0     0.11390     0.30940      0.3403      0.1418   
567      184.60      1821.0     0.16500     0.86810      0.9387      0.2650   
568       59.16       268.6     0.08996     0.06444      0.0000      0.0000   

     feature_29  feature_30  
0        0.4601     0.11890  
1        0.2750     0.08902  
2        0.3613     0.08758  
3        0.6638     0.17300  
4        0.2364     0.07678  
..          ...         ...  
564      0.2060     0.07115  
565      0.2572     0.06637  
566      0.2218     0.07820  
567      0.4087     0.12400  
568      0.2871     0.07039  

[569 rows x 31 columns]

In [3]:
data.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from imblearn.over_sampling import SMOTE
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout


In [ ]:
label_encoder = LabelEncoder()
data['diagnosis'] = label_encoder.fit_transform(data['diagnosis'])

In [ ]:
data.head()

diagnosis  feature_1  feature_2  feature_3  feature_4  feature_5  \
0          1      17.99      10.38     122.80     1001.0    0.11840   
1          1      20.57      17.77     132.90     1326.0    0.08474   
2          1      19.69      21.25     130.00     1203.0    0.10960   
3          1      11.42      20.38      77.58      386.1    0.14250   
4          1      20.29      14.34     135.10     1297.0    0.10030   

   feature_6  feature_7  feature_8  feature_9  ...  feature_21  feature_22  \
0    0.27760     0.3001    0.14710     0.2419  ...       25.38       17.33   
1    0.07864     0.0869    0.07017     0.1812  ...       24.99       23.41   
2    0.15990     0.1974    0.12790     0.2069  ...       23.57       25.53   
3    0.28390     0.2414    0.10520     0.2597  ...       14.91       26.50   
4    0.13280     0.1980    0.10430     0.1809  ...       22.54       16.67   

   feature_23  feature_24  feature_25  feature_26  feature_27  feature_28  \
0      184.60      2019.0      0.1622      0.6656      0.7119      0.2654   
1      158.80      1956.0      0.1238      0.1866      0.2416      0.1860   
2      152.50      1709.0      0.1444      0.4245      0.4504      0.2430   
3       98.87       567.7      0.2098      0.8663      0.6869      0.2575   
4      152.20      1575.0      0.1374      0.2050      0.4000      0.1625   

   feature_29  feature_30  
0      0.4601     0.11890  
1      0.2750     0.08902  
2      0.3613     0.08758  
3      0.6638     0.17300  
4      0.2364     0.07678  

[5 rows x 31 columns]

In [ ]:
x = data.drop(columns=['diagnosis']).values
y = data['diagnosis'].values

In [ ]:
print(x, y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train,X_test

(array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
          2.09724217,  1.88645014],
        [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
          1.89116053,  2.49783848],
        [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
          0.59760192,  0.0578942 ],
        ...,
        [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
         -0.70863864, -1.27145475],
        [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
          0.43432185,  1.21336207],
        [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
         -0.3345212 , -0.84628745]]),
 array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
          0.17275669,  0.20372995],
        [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
         -0.561211  , -1.00838949],
        [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
         -0.10783139, -0.20629287],
        ...,
        [-0.73547237, -0.99852603, -0.74138839, ..., -

In [ ]:
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)


In [ ]:
X_train_resampled.shape,  y_train_resampled.shape

((572, 30), (572,))

In [ ]:
np.unique(y_train_resampled, return_counts = True)

(array([0, 1]), array([286, 286]))

In [ ]:
model = Sequential()
model.add(Dense(64, input_dim=X_train_resampled.shape[1], activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train_resampled, y_train_resampled, epochs=50, batch_size=32, validation_split=0.2)

Epoch 1/50
15/15 [==============================] - 2s 28ms/step - loss: 0.6854 - accuracy: 0.5952 - val_loss: 0.5201 - val_accuracy: 0.8957
Epoch 2/50
15/15 [==============================] - 0s 6ms/step - loss: 0.4675 - accuracy: 0.8009 - val_loss: 0.3695 - val_accuracy: 0.9217
Epoch 3/50
15/15 [==============================] - 0s 7ms/step - loss: 0.3619 - accuracy: 0.8621 - val_loss: 0.2730 - val_accuracy: 0.9391
Epoch 4/50
15/15 [==============================] - 0s 8ms/step - loss: 0.2814 - accuracy: 0.9059 - val_loss: 0.2052 - val_accuracy: 0.9652
Epoch 5/50
15/15 [==============================] - 0s 7ms/step - loss: 0.2257 - accuracy: 0.9300 - val_loss: 0.1580 - val_accuracy: 0.9652
Epoch 6/50
15/15 [==============================] - 0s 9ms/step - loss: 0.1912 - accuracy: 0.9278 - val_loss: 0.1251 - val_accuracy: 0.9652
Epoch 7/50
15/15 [==============================] - 0s 7ms/step - loss: 0.1880 - accuracy: 0.9387 - val_loss: 0.1028 - val_accuracy: 0.9913
Epoch 8/50
15/15 [=

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1984      
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 4097 (16.00 KB)
Trainable params: 4097 (16.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")
print(classification_report(y_test, y_pred))
print("Accuracy:" ,accuracy_score(y_test, y_pred))

4/4 [==============================] - 0s 8ms/step
              precision    recall  f1-score   support

           0       0.99      0.99      0.99        71
           1       0.98      0.98      0.98        43

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

Accuracy: 0.9824561403508771


In [ ]:
y_pred = model.predict(X_test) > 0.5
print(y_pred)
print(type(y_pred[0][0]))

4/4 [==============================] - 0s 5ms/step
[[False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [Fa